openapi: 3.0.3
info:
  title: Weather API
  version: 1.0.0
paths:
  /weather/cities:
    get:
      summary: Get weather for multiple cities
      responses:
        '200':
          description: Weather data for multiple cities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CityWeather'
  /weather/cities/{cityId}:
    get:
      summary: Get weather for a specific city
      parameters:
        - name: cityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Weather data for the requested city
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CityWeather'
  /weather/forecast:
    get:
      summary: Get weather forecast
      responses:
        '200':
          description: Weather forecast for multiple cities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    CityWeather:
      type: object
      properties:
        city:
          type: string
        temperature:
          type: number
        weather_condition:
          type: string
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperature:
          type: object
          properties:
            min:
              type: number
            max:
              type: number
        weather_condition:
          type: string
